export const tShirts = [
  { id: 1, size: "S", color: "red", price: 19.99, brand: "Nike" },
  { id: 2, size: "M", color: "blue", price: 24.99, brand: "Adidas" },
  { id: 3, size: "L", color: "green", price: 22.5, brand: "Puma" },
  { id: 4, size: "XL", color: "black", price: 18.75, brand: "Under Armour" },
  { id: 5, size: "M", color: "white", price: 20.0, brand: "Reebok" },
  { id: 6, size: "S", color: "yellow", price: 17.99, brand: "H&M" },
  { id: 7, size: "L", color: "purple", price: 21.0, brand: "Zara" },
  { id: 8, size: "XL", color: "gray", price: 23.5, brand: "Uniqlo" },
  { id: 9, size: "M", color: "orange", price: 19.5, brand: "Levi's" },
  { id: 10, size: "L", color: "pink", price: 25.0, brand: "Guess" },

  { id: 11, size: "S", color: "navy", price: 16.99, brand: "Nike" },
  { id: 12, size: "M", color: "maroon", price: 24.49, brand: "Adidas" },
  { id: 13, size: "L", color: "lime", price: 21.5, brand: "Puma" },
  { id: 14, size: "XL", color: "charcoal", price: 19.75, brand: "Under Armour" },
  { id: 15, size: "M", color: "beige", price: 20.5, brand: "Reebok" },
  { id: 16, size: "S", color: "aqua", price: 18.99, brand: "H&M" },
  { id: 17, size: "L", color: "burgundy", price: 22.0, brand: "Zara" },
  { id: 18, size: "XL", color: "olive", price: 23.0, brand: "Uniqlo" },
  { id: 19, size: "M", color: "teal", price: 20.99, brand: "Levi's" },
  { id: 20, size: "L", color: "coral", price: 26.0, brand: "Guess" },

  { id: 21, size: "S", color: "silver", price: 19.99, brand: "Nike" },
  { id: 22, size: "M", color: "gold", price: 24.99, brand: "Adidas" },
  { id: 23, size: "L", color: "ivory", price: 22.5, brand: "Puma" },
  { id: 24, size: "XL", color: "cyan", price: 18.75, brand: "Under Armour" },
  { id: 25, size: "M", color: "magenta", price: 20.0, brand: "Reebok" },
  { id: 26, size: "S", color: "brown", price: 17.99, brand: "H&M" },
  { id: 27, size: "L", color: "crimson", price: 21.0, brand: "Zara" },
  { id: 28, size: "XL", color: "indigo", price: 23.5, brand: "Uniqlo" },
  { id: 29, size: "M", color: "peach", price: 19.5, brand: "Levi's" },
  { id: 30, size: "L", color: "mint", price: 25.0, brand: "Guess" },

  { id: 31, size: "S", color: "red", price: 19.99, brand: "Nike" },
  { id: 32, size: "M", color: "blue", price: 24.99, brand: "Adidas" },
  { id: 33, size: "L", color: "green", price: 22.5, brand: "Puma" },
  { id: 34, size: "XL", color: "black", price: 18.75, brand: "Under Armour" },
  { id: 35, size: "M", color: "white", price: 20.0, brand: "Reebok" },
  { id: 36, size: "S", color: "yellow", price: 17.99, brand: "H&M" },
  { id: 37, size: "L", color: "purple", price: 21.0, brand: "Zara" },
  { id: 38, size: "XL", color: "gray", price: 23.5, brand: "Uniqlo" },
  { id: 39, size: "M", color: "orange", price: 19.5, brand: "Levi's" },
  { id: 40, size: "L", color: "pink", price: 25.0, brand: "Guess" },

  { id: 41, size: "S", color: "navy", price: 16.99, brand: "Nike" },
  { id: 42, size: "M", color: "maroon", price: 24.49, brand: "Adidas" },
  { id: 43, size: "L", color: "lime", price: 21.5, brand: "Puma" },
  { id: 44, size: "XL", color: "charcoal", price: 19.75, brand: "Under Armour" },
  { id: 45, size: "M", color: "beige", price: 20.5, brand: "Reebok" },
  { id: 46, size: "S", color: "aqua", price: 18.99, brand: "H&M" },
  { id: 47, size: "L", color: "burgundy", price: 22.0, brand: "Zara" },
  { id: 48, size: "XL", color: "olive", price: 23.0, brand: "Uniqlo" },
  { id: 49, size: "M", color: "teal", price: 20.99, brand: "Levi's" },
  { id: 50, size: "L", color: "coral", price: 26.0, brand: "Guess" }
];